/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taktiktuk;

import javax.swing.JOptionPane;

/**
 *
 * @author Sandali Dinalaththa
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    int x = 0;
    public MainFrame() {
        initComponents();
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("New Game");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem3.setText("About the game");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanel1.setVisible(true);
        clearAll();
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if (x==0)
        {
            b1.setText("0");
            x = 1;
        }
        else
        {
            b1.setText("X");
            x = 0;
        }
        checkWin(); 
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if (x==0)
        {
            b2.setText("0");
            x = 1;
        }
        else
        {
            b2.setText("X");
            x = 0;
        }
        checkWin(); 
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (x==0)
        {
            b3.setText("0");
            x = 1;
        }
        else
        {
            b3.setText("X");
            x = 0;
        }
        checkWin(); 
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if (x==0)
        {
            b4.setText("0");
            x = 1;
        }
        else
        {
            b4.setText("X");
            x = 0;
        }
        checkWin(); 
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
       if (x==0)
        {
            b5.setText("0");
            x = 1;
        }
        else
        {
            b5.setText("X");
            x = 0;
        }
       checkWin(); 
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if (x==0)
        {
            b6.setText("0");
            x = 1;
        }
        else
        {
            b6.setText("X");
            x = 0;
        }
        checkWin(); 
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if (x==0)
        {
            b7.setText("0");
            x = 1;
        }
        else
        {
            b7.setText("X");
            x = 0;
        }
        checkWin(); 
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if (x==0)
        {
            b8.setText("0");
            x = 1;
        }
        else
        {
            b8.setText("X");
            x = 0;
        }
        checkWin(); 
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if (x==0)
        {
            b9.setText("0");
            x = 1;
        }
        else
        {
            b9.setText("X");
            x = 0;
        }
        
          checkWin();      
        
    }//GEN-LAST:event_b9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       int option = JOptionPane.showConfirmDialog(this, "Are sure that you want to exit?", "Exit Game", JOptionPane.YES_NO_OPTION);
       
       if (option == JOptionPane.YES_OPTION)
       {
           System.exit(0);
       }
      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null, "Game for two players, X and O, who take turns marking the spaces in a 3×3 grid. The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row wins the game.", "How to play the Game", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    void checkWin()
    {
        if (b1.getText().equals("X"))
        {if (b2.getText().equals("X"))
            {if (b3.getText().equals("X"))
            {
               int a = JOptionPane.showConfirmDialog(this, "X won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                    clearAll();
            }
                }
            }
        }else
            if (b1.getText().equals("0"))
                {if (b2.getText().equals("0"))
                    {if (b3.getText().equals("0"))
            {
            int a = JOptionPane.showConfirmDialog(this, "0 won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                    clearAll();
            }
                    }
                }
                }
         if (b4.getText().equals("X"))
        {if (b5.getText().equals("X"))
            {if (b6.getText().equals("X"))
            {
               int a = JOptionPane.showConfirmDialog(this, "X won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                    clearAll();
                }
            }
                }
        }
        else
            if (b4.getText().equals("0"))
                {if (b5.getText().equals("0"))
                    {if (b6.getText().equals("0"))
            {
            int a = JOptionPane.showConfirmDialog(this, "0 won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                   clearAll();
            }
                    }
                }
                }
          if (b7.getText().equals("X"))
        {if (b8.getText().equals("X"))
            {if (b9.getText().equals("X"))
            {
                int a = JOptionPane.showConfirmDialog(this, "X won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                   clearAll();
            }
                }
            }
        }else
            if (b7.getText().equals("0"))
                {if (b8.getText().equals("0"))
                    {if (b9.getText().equals("0"))
            {
            int a = JOptionPane.showConfirmDialog(this, "0 won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                   clearAll();
            }
                    }
                }
                }
           if (b1.getText().equals("X"))
        {if (b4.getText().equals("X"))
            {if (b7.getText().equals("X"))
            {
                int a = JOptionPane.showConfirmDialog(this, "X won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                    clearAll();
            }
                }
        }
        }else
            if (b1.getText().equals("0"))
                {if (b4.getText().equals("0"))
                    {if (b7.getText().equals("0"))
            {
            int a = JOptionPane.showConfirmDialog(this, "0 won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                    clearAll();
            }
                    }
                }
        }
           
            if (b2.getText().equals("X"))
        {if (b5.getText().equals("X"))
            {if (b8.getText().equals("X"))
            {
                int a = JOptionPane.showConfirmDialog(this, "X won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                   clearAll();
            }
                }
        }
        }else
            if (b2.getText().equals("0"))
                {if (b5.getText().equals("0"))
                    {if (b8.getText().equals("0"))
            {
            int a = JOptionPane.showConfirmDialog(this, "0 won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                   clearAll();
            }
                    }
                }
        }
             if (b3.getText().equals("X"))
        {if (b6.getText().equals("X"))
            {if (b9.getText().equals("X"))
            {
                int a = JOptionPane.showConfirmDialog(this, "X won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                   clearAll();
            }
                }
        }
        }else
            if (b3.getText().equals("0"))
                {if (b6.getText().equals("0"))
                    {if (b9.getText().equals("0"))
            {
            int a = JOptionPane.showConfirmDialog(this, "0 won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                    clearAll();
            }
                    }
                }
                }
              if (b1.getText().equals("X"))
        {if (b5.getText().equals("X"))
            {if (b9.getText().equals("X"))
            {
                int a = JOptionPane.showConfirmDialog(this, "X won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                    clearAll();
            }
                }
        }
        }else
            if (b1.getText().equals("0"))
                {if (b5.getText().equals("0"))
                    {if (b9.getText().equals("0"))
            {
            int a = JOptionPane.showConfirmDialog(this, "0 won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                    clearAll();
            }
                    }
                }
                }
               if (b3.getText().equals("X"))
        {if (b5.getText().equals("X"))
            {if (b7.getText().equals("X"))
            {
                int a = JOptionPane.showConfirmDialog(this, "X won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                   clearAll();
            }
                }
        }
        }else
            if (b3.getText().equals("0"))
                {if (b5.getText().equals("0"))
                    {if (b7.getText().equals("0"))
            {
            int a = JOptionPane.showConfirmDialog(this, "0 won", "Congratulations!", JOptionPane.OK_CANCEL_OPTION);
                
                if (a == JOptionPane.OK_OPTION)
                {
                    clearAll();
            }
                    }
                }
        
                }
    }
    void clearAll()
    {
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
